# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6d457b8d-e174-4ed6-a28f-c3e4b9c87beb";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" "nodiratime" ];
    };

  boot.initrd.luks.devices."crypted" = {
    device = "/dev/disk/by-uuid/5c4277a6-447f-4552-a4ab-e5c09198d3c2";
    allowDiscards = true;
  };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/6d457b8d-e174-4ed6-a28f-c3e4b9c87beb";
      fsType = "btrfs";
      options = [ "subvol=snapshots" "noatime" "nodiratime" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/6d457b8d-e174-4ed6-a28f-c3e4b9c87beb";
      fsType = "btrfs";
      options = [ "subvol=swap" "noatime" "nodiratime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/28E6-08F4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6d457b8d-e174-4ed6-a28f-c3e4b9c87beb";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "nodiratime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6d457b8d-e174-4ed6-a28f-c3e4b9c87beb";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "nodiratime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/6d457b8d-e174-4ed6-a28f-c3e4b9c87beb";
      fsType = "btrfs";
      options = [ "subvol=log" "noatime" "nodiratime" ];
    };

  swapDevices = [ {
    device = "/.swapvol/swapfile";
    size = 16*1024;
  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
