apiVersion: ENC[AES256_GCM,data:w68=,iv:OKJByBpU855Xr9Dd1j7+LceYPdvPM1c+M6Gyy/bUZ38=,tag:aKwWWY/QE4OuKwo+9Sw42A==,type:str]
kind: ENC[AES256_GCM,data:6+BeJGPZ,iv:XBm3NQXXqjGf5ZfHpHAhCcoTrzb0+Z+yXWbtgkCA8IY=,tag:5RwVoGirI5U/sqIOHRz1dw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o3hsuutX5OLIS6KrChqumA==,iv:fp5pOmn/16b6TKhNtO4R7Dxh/7143UCM6T8z9vHdS2I=,tag:kQQWrE//hKzdmYbRP8uJ6g==,type:str]
    namespace: ENC[AES256_GCM,data:jR+jz7gRDaU=,iv:aVQYGKxEpqTpjCBAHu9+QpwvyMLneLF1zAzbhP3ckhg=,tag:T481vXGZdBe9kauG5M+dvw==,type:str]
type: ENC[AES256_GCM,data:7c/Vw/Ed,iv:SG2LVndPXbTERISmlKiGcrCP9GqScZ5U3apwNy7r7OQ=,tag:R3wKKhE/Y+mrpUQrHjb4Mg==,type:str]
data:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:AsLTF6fFo4VQcsEj5bL3pPLAvKPPOS4tXa/f0TxrcAkXTKjaZNk6ttTN7eUP8oK5tmdHGzZjgkq4UJL0D7oOMH27+irt35sxM0H/7A+CBHrNXukYt0fPUh2LHWBB5CPQRL1ChYkxTmgMND74ecSJDdIThkOJ0D0hTD+VjLtBEyCeRiXXYzW8ufEZqCzb8HPH8v9+s7HWXubQDGfw+/R3dgW1jhKL+kK8xYW6bQ==,iv:OgWwfJ04LlY9zNBQp7MDep86W20NXLiOPX4kIiodsW0=,tag:PiMXK/QHOJV+W9fUZgpmFw==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:ipRT9og0RsZQpPiXh4FmyAKF1vwZXoDUrFinAW8lxJ8NpqpKUoayrO0gH9WlM/QGfg8fWzqrnKprbHLJMrs9ugaGDXE4gUNcphyZfwhRBLTlcZ4ePWjF/x6RihFd0RYhG0VpfVGxNGRR3+BfIcnrn9UZ+1mXwttTUpj0nLOY++UvRyEvkV/jn8yY84u+rRohrGXT8d9lTQK3zbbB9plkWyXCgmkMhahsJRqKfg==,iv:gIBh+5/OHOgrSrYE+BDSNAKqPncS9gQRU8mBZB2vGNE=,tag:RaC95BwQilpsV4CJVZ52Nw==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:WQM0xrPXC2PxiKIkLZ6nCpkYN7caeU463EPBmZums+07OT0+K7kUKBMzzgoXBr4bLyYtBL4/j+oJwFyReZlBwbzEylzZT2paZxyLiQpmTFmdHSikiq5WmYZqLwi+swwHiKtvwAiO/yXK26k1LBptT7+D0axJMOwA6WECc0Xh4L6Zt3dXsRe9gTRTtvQO+JGmUtBYuaCMLf767cv36SEFquLP/oBaPtCu+uT5ew==,iv:L+SF/8Jd25Fa7FQBwRaVx+cr0/EX0TWs5BxO8+cEHVw=,tag:3vyrt6gXrbh801KA0lfwYg==,type:str]
    identity_providers.oidc.hmac.key: ENC[AES256_GCM,data:6uTRbGqZl2rrC4aQIVh6cGv1GlOwBXShfIeysSOQzWu6vhjpxUORp3RjLH+qq4rM3P12myW2JwCWEALUTozMOm2VwxwIfs/0DtN6aeuRY7T01KI+Iy/Sp03AquED4UFcw3oCOlJ/4KiMoLfRKnpJsV6iTV+VWAk74iiUypbLxEG1t2g0MMdXBlFjI4loE8GIWyWIHeexfnfDlJ/BVIhUXUbVzcZ2t6TO9WbhGg==,iv:XBGMMHAUQT3pEf159RRmXq7SdCllU4ekNT9SWVpiOFY=,tag:U9J+MEqTpBo3fxIsUFb+dQ==,type:str]
stringData:
    notifier.smtp.password.txt: ENC[AES256_GCM,data:E7NLvnbxws+/tkbjp1aA0ZLw3g==,iv:MJMSnZ3N92F7Ec7hSCFVYXGLDBX7wsUCHRcLLz/P9rk=,tag:aOAaJkuZRQZPcF250ogNGg==,type:str]
    session.redis.password.txt: ENC[AES256_GCM,data:2YS+jKJyorrzvo+o812TmyMZMxkA8di6qiVnF7Ek/y4=,iv:gDEIpu+6a/4VgOrpwpSOg6yah2xTJSXWC9V6vR0yo/0=,tag:A9TVc1x9rhwJi+MyxkO66g==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVUhEb3RJc21DYTBYeHNu
            SlFVUGViYnJjZUVRY2xzSS9WRTFKbUNjWEg0CkgzL0FxT1NReS9BLy9JSXB2QjVj
            T1hoanpCWHVSaUZqVWoyYnBMalRpcTQKLS0tIFlRdm5Md28zUVBUenBiaGNDNDI2
            cGNtWTFON2svOFg3U2ppUktTK0hmUDAK03hZOj01CEAfdB1PeOxTKQWma8+Ud/PA
            vR9zW+T406v6GIYoRTLaywXVazbGIHd32u9+tE3G0adCqD7hM3DRiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0FYZmxwUmhjbEViY3VW
            UXhLRkRFV0lROFliNlU5TXduaWQvc3dvMHpJCnh1OVZaa3BudkpDZ1BxOXFPdE5H
            MXVoSXREQ20wd2dPbkl4akM5OTRVM00KLS0tIDJnYUdNSXpvVm1PUElWeTQxMEFR
            S3ZGUUk0VVhQRmZpY0pqSWJOVm5VenMK6KXB/KTYhfn6MCSonGEWiOqqEdLjeKnp
            Aw7VWyz7apbPBfL3v0j/k0lGj0dn5pHmL9blz9MY8SJp0tRv9UQ/TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:56:29Z"
    mac: ENC[AES256_GCM,data:uJASRmYSdLHuhfwUIGV5TclyTZ2NGbcpN//LnhbTcUQqJzqp1C3Ma81PVLCIbCG6Zdd2Cwyo0JeJu4doRjgAr1TgKLhxCFkVh2L/EU5xsN4vLd6ZRfpS5CsVM3oKh7I0ByU+iiPxTMLaipG8Q8YmrGFFbkHc2P1V2ItBx+yiqBc=,iv:cdsYNoKwOkvXVU3YUk3MwI67CVfLkWOs7qziDptsvdQ=,tag:xOxf7US7k8dhXa42XClJRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
