apiVersion: ENC[AES256_GCM,data:6OM=,iv:BgMvxIhdGMKXaIdVmvDSfgSjqBjRCZcccgTbmWhJI/k=,tag:AURT5Jp+/q5poQXFtVCdGA==,type:str]
kind: ENC[AES256_GCM,data:950q75NW,iv:dIO+legJSBhj3xoh1v06IM4G3SQcNFkY43ihpXVPznw=,tag:Z+dBTkpDJf/XQ6OjAkEvGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Eru5ioU5WQh3bf3xooFYPQ==,iv:m+knyQ1mD2+xeyH8eiKtBfdTAxO5Nau1c6SngAAHjHM=,tag:A3x8qCl4kfghl9WmM5DPwA==,type:str]
    namespace: ENC[AES256_GCM,data:TFiU5I/AJlcEHSY=,iv:An7TjpvT0jIDbEYzQIkJuFvDJXS84Dq83JVJsd8a+fE=,tag:Z/VKaycnOnlGnio+nzdOPw==,type:str]
type: ENC[AES256_GCM,data:D1Pny1jq,iv:mprIN+j8tC8UmMBHO4oM/u+87YZjFmmtz9ry4FbVoLg=,tag:uLQhIkvEbitDLqERGCcJaQ==,type:str]
stringData:
    enroll-key: ENC[AES256_GCM,data:UG2o6D3Y7qrwbHXUxN4Hoh+kFv8s8mVCIg==,iv:5oWOOVQYH8isL4d6+1QAB1XJ5DRQg0MWtmCcP20b+kc=,tag:enSfL+N89mDpvKXA6UnIlw==,type:str]
    traefik-bouncer-key: ENC[AES256_GCM,data:kktf53CTx5vb6LJWsueR7MCzdNQHDOINSIyT4e2o5WIPPbmW9o8vYuxQS2WE2kYiZ/Ss5zZk2yODfflU3aOcLQ==,iv:34DkdQAnlPPDqW3PfsCvrgC/XmYqEvt64RGThnxxK7c=,tag:tp8bL9ToIp9g64a385xH3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTVVqTmoxVmkrcFcwSTdN
            Yno5dlAvd05zU1BUanJRRTd6cUM0bHRSQ204CjJDajh1Qm1YUUpFNG10ZnpKNnFp
            U2NwY1RIVm13Rittb2xQaGJPdkhFbk0KLS0tIHdqUTdjY041RnJ3Q3E3ZVF2cW1y
            Y0Z2TElGN2dRekR1bXFiYUpPcnZFTlEKiIPcRnTk8bWL5Eu6fwWZxW4qq8NRBkCG
            oIsyAeNqkKbOmhdUHkLIWsbCxyh8zCS4xqn5xhtci4BuqznRueLKiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3NnMWgyNGlMZk40UlZ6
            QzZMY3VwK2RqOE1KRTlDcU1pOE9pUnVMZzFJCnZXSWVIWWRLMnBoV3E0MDhtOWF2
            SDZ2U05hd1pyN0dWSkxQbnlHQzdMb2cKLS0tIHFRTnZNdVdZNElaNWo1RGl4ZHIw
            VEdnZmVJcVhlNE5teDZZVTQ5c1lTRUUKz590Eu9JP5tZXogm6YWwrVO8b4FCFJi5
            dbTrRU76mWgmYkSzWZQR/jwy0/yPg+XqsjeGWC5/RrSinMfR5NzGag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-09-22T12:50:34Z"
    mac: ENC[AES256_GCM,data:GGFTLTCZfpUBCTxtYBd7v+bJPks4VguAE6FwdyN75iYsOQKZtcGV0+eWJ03H/iUkpTwALX/WR/AiSzFCBSrQr4e20B+JiIPxTPzGD1GEWDr4cXwMxj7nS6cEt6LS8wQnx4+ZW5S0hg58J6Nd+Nl5kkkx180yj9JeHJ4+FB+5gdE=,iv:OMeGk+hVH95W0HYGTv7OYNIFtK2ZOcoASOMHR4TQ65c=,tag:KWSvHmX6yDYwSUAluVBP8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
