apiVersion: ENC[AES256_GCM,data:MMA=,iv:a+FvYruHVDLysPxYMr58zOP9xikfjmA8qYj5vhBSnjM=,tag:NUQQn8czNmYSRqeLd6kEQQ==,type:str]
kind: ENC[AES256_GCM,data:hZjxESL8,iv:Wmhp0yV9mLMragd7MF4QTPAbCaxXLLSQsp/qkyQ6d0k=,tag:eTARGaNBZxuc4fgmTDBRZA==,type:str]
type: ENC[AES256_GCM,data:4NE2nc8T,iv:44xRCGytsqqrrGt193fe+tA8OnBkWJjRs5iGp1ycdSk=,tag:+hAyiredSC8CpdBurtJsYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JzbQNWHcc0pnYKDgvOdHsw==,iv:e/7gFfdOQ7XIx6CaaTrVvKtN/8mMFNvjKRCiTA+dMbI=,tag:a1LMt6KHwn6MjSzBRPGh1g==,type:str]
    namespace: ENC[AES256_GCM,data:+K5nC7NGSBg=,iv:8cyFzeR56xJbx4t01/hLNh2ckPJxa0hhl1xpwvVDu8M=,tag:gcX6q0Vb3Nrup6SgAyp0cQ==,type:str]
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:IB9SdnURf0e9fCuqq+xKxgSeFID14fsC/nUa75492dC1QCJNMhk6QY/6M90VppyFPYXD+kra9/7pjv/s0iEVvB2OVRDghqKp,iv:LmMp747loG29/iteFeAQzyuArjweAxsp1mDSe6aVQA0=,tag:/w0+zehNjREf6ajEPOne8w==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:Zlyofhn5FOWgTtG1UBz0xYjLJZe6OddqUt5+/91xK741qvu6KyRutbVKhb8isgUEd5Mc9OleIBwrSF9Au0UsbA==,iv:v7GIrg4yLjfiLH3sQ2s4o8udINE6BHkdRR6Q1Hc4MEM=,tag:tYaRxxEVFfh7c/JtWZkY4g==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWXcxTUNxa3ArV2g0S1FG
            dFJYQlcyQlVxSXUvcjJZT0pNU21qc1ZhS25NCitrWkNYZ1J0a3g3WURDcTEyRjBz
            WjA0TUxzRlRyTDd2cHh2SS9DM0x1TUEKLS0tIFNra0xkcldKR1d6VitxM3RkYlc3
            QW41dHBxcm1QY0Y3V2FHUXczRTl2ZE0KqScfDIXPMvnX+bNs4gON63K/mvu7mMvu
            wMWiZsQpK5a5GiZ7lPDyr5Q1zsqrMADjMHM6pnpfP5dwx0MfrfndYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmk3eHBDdGpOWm51YTB1
            Sk0zUHNzVm1PRzJYTU8wTTdnR2twTXVUK2d3Cmx6RGV4YlhyNmNZa3B5bTdEYk5p
            MHk1N2lUajJ3RWNCV1duSW1EOTZRVmcKLS0tIDhWZkNWNFpCdmFUMUIzQitoNExa
            ZkU4SGZDd3A1MkRreWlkNDVvdXM0TkkKZQQp86J2jkFp4s4ouW2XNi2anulRSuMM
            dLJHQFyIaeatHp/l1dnXQ/bMx9NO55b/gEeRfQRT9jB2DBlJGVqMig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T21:04:51Z"
    mac: ENC[AES256_GCM,data:OpKvewpm4pGntYZ3rSAIRhbv9Ze3s8b/DCQO2dzSNKjSO2MT3ywRkfuzZp7fUMBnjdaD5HiHZmspU0jqTJctHIvLgHed43RT74jf8pRNPxTuGP5Q+cXA0H9xJ6s8vgb2zMtFxLtFu4BdYGZi7jW7Ezb8T0ctgeRywnXFt/NxXdA=,iv:B8QgizqS5pPyunrKQSVJV/c5O+tnLhPio4Iy9mDJv84=,tag:bn/yFPhUQxVoPGTmuGE+Ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
