apiVersion: ENC[AES256_GCM,data:U1E=,iv:EAsyPkjiq/rvhTDWY+V4Z29D45/CPJT2BWWIzeYb5rA=,tag:o1kESRmcmwvN6H8Fs6b7rw==,type:str]
kind: ENC[AES256_GCM,data:PuAHTUYQ,iv:2ycx7WsjHIGdw5BuUCtd0/1OA8s2J5hwop0ytourwcU=,tag:VK4NHNrFtNSbEerl06V3FA==,type:str]
type: ENC[AES256_GCM,data:i3mIBveg,iv:2V95cviyYQuze/piwb18C2alrKFfFAeT967/qV2nc7A=,tag:iou5bRy3FX21fGSutdFRJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AHp8MHxPiU9ltcC9MCA=,iv:GJx0ltMaeiiTODFGuWHruhgCMOqB3fXxReg4/ZNAQZg=,tag:47mrh3r2uyfRpxQ4c2EkEA==,type:str]
    namespace: ENC[AES256_GCM,data:3MTH4yyX,iv:7pM0am7VdP4u3p6nyFkrJMDvmOYw8ucNhyTlSmJlQec=,tag:bDkZ8gsDYx+ZoTpN9fMa9A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:J8wPNzLk,iv:3RsbZlpWEBCD4q6v60rq3Jv228l2InRzn8wkgbujZyo=,tag:1J0HsT+5wuyFmkwdPqnCoQ==,type:str]
    password: ENC[AES256_GCM,data:wOEYetQU+aP8UxwW0txfFUmsDqPZrmJBN/Mhmwwyx0k=,iv:leyQvw6U4X+AT7JnsqQHNb/D3CH7RR0uEoJOmcdWlLE=,tag:qSAjORHPElX+Uv2HOTMDJQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:VI7N3bLjzll+l7EfjsadbwDXXzER2SakGSJEXuITpUoyFy5nC+rrD+a3b5DC4IRS+6Ei3COB14P25ZKz630eV5r8AsBPp7CmCxGzgf/ERb5np50=,iv:HINDj0qbktq0LRzZySKzh44FtLVxS6rNIOmjHuhwR9Y=,tag:ShwHh+D4v1jUjRtzQkpA9A==,type:str]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:fKO/MVyOPjP6,iv:kywoi3gJUwd3ukCFntoH/oMn3NI0jOayk4TUmEN8ZFA=,tag:I8oNKYUNRADsx/WjjJ+iDw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:wFUy7CM55po=,iv:VFFM5Oy9Vx1RMdF5PI4BaZtiI7mFvygLuIVNfG9KaPE=,tag:I3Xw8FgJDM9cF+oxu9YZGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqelNsTzFGaGRxbEJOVVB6
            aWt6ZHZJRDFneThaQVRsSFhiZWNXMUxwcjFJClJydUR1UFd4TldlS01DV3VBV1pu
            anBubjB2VXA0Q2xlNlhzQmtRQ2ZPL3cKLS0tIDBOUlQ3Y2FMVjh0dGQvSERDb0hw
            VWpaakpndU5vS3RjOVFkbjlNS3c1b28KlpTwbUmreitzQeMNvRyWRPT1f3gKsVal
            xVQTCpQSrYTTiX7NejhyslK4hZhViB24qaiPDUzrStqdY8DSJ8LnlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMnRnUXVCcUNraHVBK2I1
            V2NxQitTMDhEbnQ0NzEyZUtjUEFFYWY5Sno4CmpaWEpUMWwzVUU2QTFBd05VMkow
            OHNaMjVMek5MUlVMR08vcHFKQTRJb0kKLS0tIFc5RXA2ZkZDbm5kQzQ4WnowMm53
            Vm5OaTRZVjZwV1FEVGliU1dLMFFra2sKuHUHLqomIR/HDHP8Yd3oFQDFAR8QlYYe
            XZy8TnS54AWjNIn+jgjwT44BgiYIufGVzZBLiLHLxbwdTp4sGZkjlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-07-07T20:07:52Z"
    mac: ENC[AES256_GCM,data:7HUhhRz8aET9JBZEBgf6aZ5saAd3Kl9qjeHPRNq8f9AHTQNpthEvvKdW+FlWMccd4zIGNDWkEZOHccbcz/ibZWh6gGQ5TzDyoILCYgVs3F5JDFX3u3ZjLsDiiEUum4Fm6Oj0XFa051bzKWlerXCGakGloUMlR+2GnczcI3pycXg=,iv:JMtxeqdL9mZwl4bIWQCLnmB+mV7dbmwXhcuznagLido=,tag:sM0Wmi3sAcZYix+IRWMvFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
