apiVersion: ENC[AES256_GCM,data:vJw=,iv:rojv4KIXSys37eLCxVKHZibT4sfavkHGZ8gE6PpLp7g=,tag:Vl5nsXnhtM/00qRhiZ14gw==,type:str]
kind: ENC[AES256_GCM,data:XwtAXIX4,iv:WRVdWEjQcosBBXHNhI8iBRNLvjWo/BWlRBtzPhaOjl0=,tag:7OppBulLB1SlWgvvxgfvCA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ylj0/blmK0QiwzWw9/QlltVn+2mU,iv:/6IykBFDtWVpArtFJCteyl4VuDUVc2D+OOKLyJUNBhs=,tag:9PkEdE3UT/i1AIkFDCopuA==,type:str]
    namespace: ENC[AES256_GCM,data:NRxbSGUG,iv:ShrF5UmBx+HTpbOxvYe6B6/G4yIBdeP6zW4PSwUani0=,tag:dGvR3G/b396Br/Qg82ufGQ==,type:str]
type: ENC[AES256_GCM,data:/PCQ+z4i,iv:FBMMIyshyDM+OSKUL5fleVbWfeX/C2ZM+3ojN4cZHv0=,tag:cJ517LsOQW455isejWJxoA==,type:str]
stringData:
    rclone.conf: ENC[AES256_GCM,data:PwCKc/sf3x6K4VC6ZymLbLvHCaqUHbmN7M6kfQO1TIwd8i1WkGonVFS4EWdMRE/GxmwsRIfAUlLOBtTVSgGWY6mUQtiyss0V5T5LCb5LdH8keyxXmALq55XPQUagXuoxS5WeteqoH3UksiH1m0msCsiur1imNYVHYWz2+DoS+EaPinBNjDg1vaSdyuTZDlbKB6AdYJfGsRrbASm+MQuqPyMlVwpOtM9FSathOmpBB9o+VId7MX8CAuD3Uqh8SASe7oYKnvZLoSAWA7zCc3QLelRQOWld8A2+KhN/9YZRLBNVNLIUKGiMJ3ZQmwteTB12nw2Wtm7cW3aFyaHPe0AaQxjTIOFdkFgRsSHywfQoxKMBKQAvlHKU7tSNEZKmbpvgI+IAJokQb6pL3B0hNP8URtyzKU60lrlGzU+hpWaC/MyxTf5pDUOK6Ag/HtNp6NICT4Azkyqzz9MBFEfDwpzEfUA1FEnoHtoBhgN0ETbDtbV7Wq4sNiKLWD3jezzIJh0C6Z4bl/IMxWmr2K93y7ArKlMa9+UzfKxkH0nkjqAwhXy4YiOZ60lq0YfDu7j5xxwD8AImGihbwQnk7vh97ReCF3j6EInifrd7X1CmS2NMR7ImZDrEexEvBOYna94VsLkMNA==,iv:hBX22ha3m/ixgwqRlTu1VpYD33Hhn7gWlEb4yJROsgw=,tag:YrQkTe3W1ft+50kQv3SSbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcERxWVNHNitqVmFZRUpZ
            WEJha3Uwb1lPeUI1dlpFTUlzSWF2T0NBcW5nCnMzcDE0WGwwN0tLYzJaTVkyVXgw
            eko4MXVNZmJvb0VHUUp3QitkWUhHYWsKLS0tIDZJQ0VjYlJqUFVVRlhuM1ZOem95
            UjljYmlTd3Jad2lHMi9IUm1PT25EdlUKAHTeNFTPxX+l+IGIK7Z3ukb6YrAbWFRo
            yVeuXB89egPJn0F9UfFcup8Q1Ghvwx+MnXjvXhlJB4GFN33BTENdaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUktLN1JHOTBhRVhQZm9m
            MmJGQUd6UkhFaTk1VDJVMlJpNW5iR2R3SFZvCkY2bWdYbE9TWTRBMWc3OUpjZ2R1
            UG4yWWl3WjV2VGd0WWM5b2xYS3g3dkkKLS0tIHpFV3MvWG1ZYllxYlN6WmVVVDBZ
            R0FoU2NocGRXZDlnS2ZYdkxsYkY3bG8KsbmSgzeGpmAySJzXz7RQPU9MH6I4VPd2
            XHjSebVm1Qh3rHlrt1T7h0BF6vOBWyEkngUsOps+VCKUWt7ZutSu/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-07-23T18:56:40Z"
    mac: ENC[AES256_GCM,data:XGRl+cgXCBBNZEthAy5PGeaD8oiFvZ2A1IS0f0nh8laVSWO3rE/tK9C4hBJXfpNrTmhHuoG35YJHe4UZDZb7HTWTBVpw/KnBW4K6sf5r59mD8GsKB0utfFdqC8/X+K2R3eBn24iphZG6EmODWd2wD61VZn72FEvlEWuXjUCtPJg=,iv:ccFa6OPesrhh9yJ3BycSYtjM/FZC6mtgtVWflFoS3mk=,tag:QILpWUf5ISo7muG4Hwk1Ow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
