apiVersion: ENC[AES256_GCM,data:MMA=,iv:a+FvYruHVDLysPxYMr58zOP9xikfjmA8qYj5vhBSnjM=,tag:NUQQn8czNmYSRqeLd6kEQQ==,type:str]
kind: ENC[AES256_GCM,data:hZjxESL8,iv:Wmhp0yV9mLMragd7MF4QTPAbCaxXLLSQsp/qkyQ6d0k=,tag:eTARGaNBZxuc4fgmTDBRZA==,type:str]
type: ENC[AES256_GCM,data:4NE2nc8T,iv:44xRCGytsqqrrGt193fe+tA8OnBkWJjRs5iGp1ycdSk=,tag:+hAyiredSC8CpdBurtJsYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z3wPrFfb+oCowi4dyznbEIo/,iv:c7JZq4FP6VMRD7IxQ0/T0wy5+lz5fQMECFRxvYmPEbU=,tag:GToT1qhZu8lYoFpqdp1JXA==,type:str]
    namespace: ENC[AES256_GCM,data:w8OqNKq1PK0/sg==,iv:rlgMjnyJByzTFAyubjVaVzsnsJqdyCQu5vFgl1uW6FU=,tag:49hly4NhexL3fsBHHGSRug==,type:str]
stringData:
    username: ENC[AES256_GCM,data:sGNY58+MH6N/Sg==,iv:KnZGcjjg8Y1NA4JVRWRS0RueG4/f7IS1Dxw7qMUpX/8=,tag:wkrNijk6/e4qCYmuM2cssw==,type:str]
    password: ENC[AES256_GCM,data:oV+a1etcjB4fhWFRt8qXzgRkjzCSxRJDYViyHk5i,iv:iF4NrtsQ08aY4xlJVwrxFeYbkP0UO7ycdwWyq2FA8qg=,tag:U+O0Rr1m+KbPTvZse/9dPQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:NJ3H5Q8UsNKbJL1Ahi+LpFHBgL4zFsGXa3MZE4fuICyWUT0NaoImgjpAfGUWetr4Xp73k64wjrIrEPX4p9g9K95u2N6FC4N8V96BiQ3TgWRwDse2T21Y9Os=,iv:ILzPCYPYtaKAPIjQ3j/6yyjioyQzg9i0gmPkmK4bTgE=,tag:o7SS++yHv8mrPwlkPFI3ug==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:+YosxqWUkvily41eJHiC8AG5rVofWH8/WUYO60FEwOg=,iv:NHoJPmxv81Fu27FfTkGZ9JXX3zKuo+zEuO/FQfd1nc8=,tag:zvtfOssKJacTnRes1ArFow==,type:str]
    AUTHELIA_CLIENT_SECRET: ENC[AES256_GCM,data:jILrC8mCbzhZRNW2yyNOLkbE4eGixUZMZQfm6jhBkVOuj9ArmYbLhLvV5BXpF2H7jlmKLhAuZ7DAnjOeqIHkLBWAnSzMdyyc,iv:vuPr4o56qVL/Hs2zKeAsvra5HnRLlNtimqssw8LmEas=,tag:Lu9NNh/UFFHZ2W7Mbr46AQ==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWXcxTUNxa3ArV2g0S1FG
            dFJYQlcyQlVxSXUvcjJZT0pNU21qc1ZhS25NCitrWkNYZ1J0a3g3WURDcTEyRjBz
            WjA0TUxzRlRyTDd2cHh2SS9DM0x1TUEKLS0tIFNra0xkcldKR1d6VitxM3RkYlc3
            QW41dHBxcm1QY0Y3V2FHUXczRTl2ZE0KqScfDIXPMvnX+bNs4gON63K/mvu7mMvu
            wMWiZsQpK5a5GiZ7lPDyr5Q1zsqrMADjMHM6pnpfP5dwx0MfrfndYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmk3eHBDdGpOWm51YTB1
            Sk0zUHNzVm1PRzJYTU8wTTdnR2twTXVUK2d3Cmx6RGV4YlhyNmNZa3B5bTdEYk5p
            MHk1N2lUajJ3RWNCV1duSW1EOTZRVmcKLS0tIDhWZkNWNFpCdmFUMUIzQitoNExa
            ZkU4SGZDd3A1MkRreWlkNDVvdXM0TkkKZQQp86J2jkFp4s4ouW2XNi2anulRSuMM
            dLJHQFyIaeatHp/l1dnXQ/bMx9NO55b/gEeRfQRT9jB2DBlJGVqMig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:52:09Z"
    mac: ENC[AES256_GCM,data:4MQIxCWSSsi7c5cZyRc5WrLaKzun2PS0Hbg4XsQJMnK5DWeswkwbMIjPASzeB5GL/HglSEd3Jtsftdqb/Vjs2arkqJYlQphrEbFlEtmulFBfLR/FpCnpClADS+1YejP4FaVWVmklQOywoJFVyWRoSzW9HGyGE1Ahae1d6DIv/OE=,iv:snIzrVB0kC3wLW9sfpy5+PuWKDSo3VfH/OTCQaCDxcA=,tag:l1xncS3ejzx3Ph6oZZG+rA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
