apiVersion: ENC[AES256_GCM,data:oes=,iv:XHExAyAmobPeVFhQorBWXgGX5otbUSmC5NXYguxEOwY=,tag:wD0eEIgggpbcxaygpgRAwA==,type:str]
kind: ENC[AES256_GCM,data:uMMaoqkc,iv:4upPbU1f1o1lJG/7Ac5scL75JA12f3QN0y5Xb5HVfpg=,tag:8vUKYu4t+rCIFJo8Azw6YQ==,type:str]
type: ENC[AES256_GCM,data:TAvkdouu,iv:YvmUjiAzgW32tXxeQutkpr+FW1q8wyUdGfF8yV337ps=,tag:wrGukB+O+9Oi9LvhtiLx2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AbiYCBkj0WPcDN0R7WF91Q==,iv:o/7ttgDeFjLLZEtcWc0p889tXtjIwBJNTE+RetCo3FI=,tag:3fs/ICldIljkKrQtPpsyKg==,type:str]
    namespace: ENC[AES256_GCM,data:mWmudj/Sy0+l6qmF7OVQ,iv:vKZAwy8i9pbv0M2TJ/4hW/+Ucxtu0KCdn0nQ0z7k+h8=,tag:g1rGhtAE4o2yDJzBOOpWnA==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vMD6VPDVODrS,iv:5siyMcxJf2ML2xRQhk5QQPJdVfjZiZHdYkUvPXx9JNw=,tag:MlUCCP8tQBnZldIQUBZj6w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fVOxnb8Fil8=,iv:PuSaB+6RGPj0IgziLIKy2UCU4t1WlkKKcL7K2RIDdOk=,tag:vx7jq1qbeAyRMLYsW8ERZw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:clMUtb3cttrqBY2RuYYfLFhFba5aUQj22MNNBiQhXYEc/PjePhAIeODwTFh+lAcxxA==,iv:Px/1vndDh9iaWKCF1FBTyBYkvZco5gG3Ft9IRDTypkc=,tag:zcg9zlzee0JolxErWJzt8Q==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybCsraEN6V3hwZFZHK0Rx
            UjNYK3EzM25ma3Z3ck9zeVlVdW1YZHFNZ0ZrCnNSMjczMzJJV0c5TjVyNGowUGNo
            bXZJVTJIMzJtdUl0bWhaWkl0UjNrVTgKLS0tIFloOVNiYWUzL1ZpelZjd2Y2clBS
            OXdSM0UrdVpyUWo0b0p0R2tkNHRNclUKcbmIeX69QwjJ8vogS44E01ozkBxtQvlv
            3u0N/O/U/j5k5qwEDf38qdtg8bkoKcTBFpDhrYcnKpscDYvjJQuPXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHJxSFhIUW5oRWk3K2Uy
            bVltck1YTE5aNHIxemtvRExYY2ZzMjYzOWhjCmxMakJvd2ZqQ0tSdHFOYTEvTnVM
            TUFON2VPZnhzYzdwZzdlaHRzbTJVRncKLS0tIDY2bS9QQXpFUXhTWFN0TzFGSjNU
            alpJcEpEUTNCejRScWhSRTcyaXFXREkKbJVOIjhiT52z/WfRaFr7jviBMmZEYecL
            YRx3YxcFTCIjZWFtBcvPJjcEv/KGzndbFaInKuH2E8FyvYtQGORIuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T17:36:08Z"
    mac: ENC[AES256_GCM,data:liecMOxqm/uFy2buaCapoTpTZOZOWtRVQgS/TJIkZXRl2Rf3CLDR6QTGSklhABzkC5eKtziKJ8OX/KUfXr9TI4CoRkRbVt/ERauDQBT9rKjbeWgiusJo9hL21TvuTW3FHNUMKpc2irBRCty+dLk+mrT2y0fJIPaQqsNGnjxAQqA=,iv:7cOtDjS/AWD4zX9ZvDbZ1kY6abbtwOsY74niEslLa9U=,tag:oUmEADJ+SIHf8gdR0Ucl7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
