apiVersion: ENC[AES256_GCM,data:oes=,iv:XHExAyAmobPeVFhQorBWXgGX5otbUSmC5NXYguxEOwY=,tag:wD0eEIgggpbcxaygpgRAwA==,type:str]
kind: ENC[AES256_GCM,data:uMMaoqkc,iv:4upPbU1f1o1lJG/7Ac5scL75JA12f3QN0y5Xb5HVfpg=,tag:8vUKYu4t+rCIFJo8Azw6YQ==,type:str]
type: ENC[AES256_GCM,data:TAvkdouu,iv:YvmUjiAzgW32tXxeQutkpr+FW1q8wyUdGfF8yV337ps=,tag:wrGukB+O+9Oi9LvhtiLx2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AbiYCBkj0WPcDN0R7WF91Q==,iv:o/7ttgDeFjLLZEtcWc0p889tXtjIwBJNTE+RetCo3FI=,tag:3fs/ICldIljkKrQtPpsyKg==,type:str]
    namespace: ENC[AES256_GCM,data:mWmudj/Sy0+l6qmF7OVQ,iv:vKZAwy8i9pbv0M2TJ/4hW/+Ucxtu0KCdn0nQ0z7k+h8=,tag:g1rGhtAE4o2yDJzBOOpWnA==,type:str]
stringData:
    CIFS_USERNAME: ENC[AES256_GCM,data:a7fMjAssFhY=,iv:Z0f6KC+0NGQyd0TOmpqimi5HzuOno+QSej4FhISgZ4A=,tag:VOAl5vdzbi2Oyzl7VdMiYQ==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:YD99DgQ8X+D3DnoHE5TWIP35FPRwrM9cM20N2HSN6ytRpkovi/ORMKXlV5pRjPj0UoG69ZMHBm2/+wBpo2U7jQ==,iv:Yv/ElZ5eABp9Zy4XSWhvqmPA5ONMAVTUr3ouIQHTzrE=,tag:iH7wLjxk6zIQlY55f+GW/g==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybCsraEN6V3hwZFZHK0Rx
            UjNYK3EzM25ma3Z3ck9zeVlVdW1YZHFNZ0ZrCnNSMjczMzJJV0c5TjVyNGowUGNo
            bXZJVTJIMzJtdUl0bWhaWkl0UjNrVTgKLS0tIFloOVNiYWUzL1ZpelZjd2Y2clBS
            OXdSM0UrdVpyUWo0b0p0R2tkNHRNclUKcbmIeX69QwjJ8vogS44E01ozkBxtQvlv
            3u0N/O/U/j5k5qwEDf38qdtg8bkoKcTBFpDhrYcnKpscDYvjJQuPXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHJxSFhIUW5oRWk3K2Uy
            bVltck1YTE5aNHIxemtvRExYY2ZzMjYzOWhjCmxMakJvd2ZqQ0tSdHFOYTEvTnVM
            TUFON2VPZnhzYzdwZzdlaHRzbTJVRncKLS0tIDY2bS9QQXpFUXhTWFN0TzFGSjNU
            alpJcEpEUTNCejRScWhSRTcyaXFXREkKbJVOIjhiT52z/WfRaFr7jviBMmZEYecL
            YRx3YxcFTCIjZWFtBcvPJjcEv/KGzndbFaInKuH2E8FyvYtQGORIuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T18:08:09Z"
    mac: ENC[AES256_GCM,data:eKrth88Xa42NICgE5YSkujy0AdtvKP1NL5e24qd8/IfgYWhxucjhC9yKzU3uVD7mt2zBwy9cNqVu/NXngHhjkDZmAwrhuEWpB3tRcVBKHgNikqH9r+D7bbguxGpHxPDz1uEwA4Sy7dE4Lq7nkOW6YkzFt8d48LTJiLjUmQCiThI=,iv:T/nxs0M+zHcfEkCrvsHRCBu7PFpzPgLcndkK8bKNQRQ=,tag:l0afu3+yGCKB5suMEJ+kyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
