apiVersion: ENC[AES256_GCM,data:OuY=,iv:tpgPGNL1gg9huUAkE7Y18JmTgRWgqO8ryTo2tPkaeP4=,tag:m9rgXTHByHVkA2jjvIy24g==,type:str]
kind: ENC[AES256_GCM,data:5Iv2+80z,iv:OL2JLq4+Y2IQYoCYr5ExxSOJ/Qsei/WDatxOjyHwfww=,tag:JiMCYC0Crx57GI5hUP70FQ==,type:str]
type: ENC[AES256_GCM,data:gajrYBx1,iv:6Wb1RYFiVP/mGIAXMNkrrwaDg5XuVh2pJ4bBT7TxxgE=,tag:MiKYsaas9migmmWWGXSmXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r9l/Uh/dM3VdArkeRuaE37o=,iv:fbLqg2HLN5Yb/ZJQWB7yysgxPHlZPTq5TbdLYd/XXpc=,tag:gg9j1ORwAStpKWU4YBTllA==,type:str]
    namespace: ENC[AES256_GCM,data:jvdwSOLCt0ZD,iv:JpCAhAH14NWhQWaYf25PV2uhlMNzdxGk8OlVMI0Ohcg=,tag:TeuiRCVenisYukqDujbBAw==,type:str]
stringData:
    #ENC[AES256_GCM,data:5lnC3bkH4+iR/SVnRA7lOh4q,iv:TeAoza8B1bKluQ1YcC5Aiu6VgNJYU8GpwkIxoZcydD8=,tag:2yzgQi/jt2ZDGf+AQLmu2Q==,type:comment]
    username: ENC[AES256_GCM,data:L+Ug14HA0/oC,iv:EjNf5rJB2xduhZVoyg1LHgq2JEuzztJYDYgcAt9+w+I=,tag:3FAv24cdi7Ahiw1jAVKGUQ==,type:str]
    password: ENC[AES256_GCM,data:El752wv4x4Jc0tuT1N1OArwgWuD96JJaH8EVjmF3Yd/KgnnagXSHcbJJhHQLLwCp7vGFWVCL1P+PUKFpGyekMA==,iv:KM5SCELPPQYfvTJ4y8Pwsa5B69bggvtYWZ5e8CYmmQM=,tag:mg/u5Ugh9OB4M6FiUx/ftA==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:ZujAmZI=,iv:0GfT0Ge7nrG//qFnpehSkQjXd/uhWHRE/jgg/HWh8Mw=,tag:CjdylycLLarYIb3NpfSSTQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:hfCDtttcxyOkuMp/gQDbw0mAphXcPDQvY+rrAo5QfwyijSHJtWzBaOeOka23E3NElm4lOhCHuYE2vQrL7jSCgA==,iv:ckqITOHnaL0U/6/t2HAB222gZqAvvcub182JlEgjO0c=,tag:OkoLtYrQ+x9V06Ro+A4VOA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:D7TO+TB4SEvlBV6ExAceFi54bZacQUJTL4NNRdJ3UP+daDlBHpepHjvgR93C2t25RI8+B3NQZDaAalmDzEROSGvdkREmPslW,iv:3OTwpkKtNTxJufwDPH2iAGQGOPxRBxNfWeNvNky1FPw=,tag:/y+BImuBgUnIruXQNL9g+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAralNTWHZyMFFLK0YyWFBl
            M2NmVnpOR2hxNFZuZW1WS1JidXZqRlVrcFVVCnVla21vOEJGK1ZQcXlhbSswVnVr
            VmlrZ0hHZlNKVEV6NUg3ZnZtMmlCK0UKLS0tIHYyRHYyTWQ4SnN4UHJzb0psWUR3
            dDBWSXNRZGRET1lzSHFMWUlwYjRUMjgKS8dEmaZy4vxtbttvf/zDRNMb1geQhqAz
            94ouRKNRYCvti1MKe3XJjhh2lzGtJO70o9dMZwDNfzB9YC0ltcuDjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRi81bzhndjY5SGp0T1pR
            TE1RSEMreFV5ZEtpR09XaVlHeUNUMFNiOURRCjI1WWtkVFBCY0I0ZXVGb0hURCsx
            S1YwM2o4ZGNPZHQ5RFh2eE1TdlgwaFkKLS0tIGJSbEtjS1RLMklraHRyaE1qcml2
            aitrM1BoSkltTTB2MDJ6OWQrNG1XL2MKn79MQmlDyc9ovKCSMHXc7gK4YWhiMIOc
            6SFS/E3BTxNiZ0+QiPGKn+cFkkv6A0cw2FYQ9tsD3mSvOBdLOU3BcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-06-05T19:41:44Z"
    mac: ENC[AES256_GCM,data:kzRE9O0pl/hSDbdt9jTSp1gEcUA1tg60pBQT+TyV46yjBzxhQY3iwNXPeJLyL/MkcD2DOe9u9dns4SZyPJ9UkkJjnbXL+SeCw1bY8iaqqCB6VQccl7LsbfP3PJS4Sdoa4h0G8Ai1Y4wNlDIX5+lxZ7LjvFL1LXxVeCXLwXxKLvM=,iv:+2xXXL8CgCNMs5tXac9fr3O9a9CuyBZKKUQOiNWCVqU=,tag:bEs3dIca9nocS+ON+pGq9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
