apiVersion: ENC[AES256_GCM,data:OuY=,iv:tpgPGNL1gg9huUAkE7Y18JmTgRWgqO8ryTo2tPkaeP4=,tag:m9rgXTHByHVkA2jjvIy24g==,type:str]
kind: ENC[AES256_GCM,data:5Iv2+80z,iv:OL2JLq4+Y2IQYoCYr5ExxSOJ/Qsei/WDatxOjyHwfww=,tag:JiMCYC0Crx57GI5hUP70FQ==,type:str]
type: ENC[AES256_GCM,data:gajrYBx1,iv:6Wb1RYFiVP/mGIAXMNkrrwaDg5XuVh2pJ4bBT7TxxgE=,tag:MiKYsaas9migmmWWGXSmXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RCzj3JzT5mxZPw1wOkP6Rsyc,iv:lbu1AqhlpY+lbyVVeywapT5oYHY7e6BOH+pQdMu35XU=,tag:Dwd+tDL/ei8x1FRQm76Q3Q==,type:str]
    namespace: ENC[AES256_GCM,data:O/t3I86WvSkaYg==,iv:aBvA3W2rSzGtg+oot4lalfd+4NFL2Q/cT+AN1XiZHoA=,tag:CDBc/lEWFe0KV4E56Lq1uA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:El752wv4x4Jc0tuT1N1OArwgWuD96JJaH8EVjmF3Yd/KgnnagXSHcbJJhHQLLwCp7vGFWVCL1P+PUKFpGyekMA==,iv:KM5SCELPPQYfvTJ4y8Pwsa5B69bggvtYWZ5e8CYmmQM=,tag:mg/u5Ugh9OB4M6FiUx/ftA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAralNTWHZyMFFLK0YyWFBl
            M2NmVnpOR2hxNFZuZW1WS1JidXZqRlVrcFVVCnVla21vOEJGK1ZQcXlhbSswVnVr
            VmlrZ0hHZlNKVEV6NUg3ZnZtMmlCK0UKLS0tIHYyRHYyTWQ4SnN4UHJzb0psWUR3
            dDBWSXNRZGRET1lzSHFMWUlwYjRUMjgKS8dEmaZy4vxtbttvf/zDRNMb1geQhqAz
            94ouRKNRYCvti1MKe3XJjhh2lzGtJO70o9dMZwDNfzB9YC0ltcuDjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRi81bzhndjY5SGp0T1pR
            TE1RSEMreFV5ZEtpR09XaVlHeUNUMFNiOURRCjI1WWtkVFBCY0I0ZXVGb0hURCsx
            S1YwM2o4ZGNPZHQ5RFh2eE1TdlgwaFkKLS0tIGJSbEtjS1RLMklraHRyaE1qcml2
            aitrM1BoSkltTTB2MDJ6OWQrNG1XL2MKn79MQmlDyc9ovKCSMHXc7gK4YWhiMIOc
            6SFS/E3BTxNiZ0+QiPGKn+cFkkv6A0cw2FYQ9tsD3mSvOBdLOU3BcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-05-25T20:11:27Z"
    mac: ENC[AES256_GCM,data:KaTZgsdmbejffcPOel6+cmOAiX8R7L4VKS5RO5jTcfOalXO0aJGVkbZ9RQmSQuymGVgAZ+r4T7bW/kW0wTaPN+yXsPgOJVjYEFe4hR0AHMJeiY0XD9EsRLK5jVKBMKawPcPViJ4apV72l3i1xe1LBDKKLq7SHwF05ocNaetDKTc=,iv:Y3SyzSL75i4/fifbzmQZIHEoxdQsnV4/zLblnFvj8ys=,tag:e5bYaDSoUzyChcsBmkVsXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
