apiVersion: ENC[AES256_GCM,data:Qag=,iv:o0b8X8MPwdcPShHar0lue6ewtL0zu69HvXnLShL2JE8=,tag:Ux0ap1U2Pyzb90sXRTxiKA==,type:str]
kind: ENC[AES256_GCM,data:irIg3oWw,iv:v0qWzl4TIkdlYeiK5DDpJp813Ohu/7sY1Gk5EMcczHQ=,tag:vYhxORascq+uxp1Fig4Pcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nbu+y3vN+ydswgNSyjQy,iv:y6HLvsf0PBJ0bthFNXF4d9dorlgbko3+xKemd9Hkrug=,tag:aK9SbCeq+bcJxxI8yHwaEw==,type:str]
    namespace: ENC[AES256_GCM,data:63iFb56ZftZoJSk=,iv:1QZS066WTVt2/s8FztSSzW7Q7zZFJWe3ImgqUD8Ky3c=,tag:ac6en96Jx0A4BLiS0OZ0Zg==,type:str]
type: ENC[AES256_GCM,data:bH6ysWwe,iv:ce3XUJLdWsZ7hTwOvpaxeY74+mxVtw9U3mRf6adb0Sk=,tag:t5xn9jnG9w9Dt/0Q7fPqFQ==,type:str]
stringData:
    capi-machineid: ENC[AES256_GCM,data:BnRbVjgqfVyktoe46S/KKOi3WMCXGOl1P/YwiLiMLatId3T+PUufbXzsGEi05N9B,iv:dbosAfH4RaRGlzHKnaLj1gp9NWnh7YdrnSn43hpqHBY=,tag:SW01fuQznhVoDg9revddRA==,type:str]
    capi-password: ENC[AES256_GCM,data:IThJW5JwsyZ/aux6Mxp6PyDKQRUHp6YCMK6UUAB+pKbG2rFEUm8f2aCWLUjBqnhKqM+LOVF11pig6ubfbwK2KQ==,iv:k4zU6sSIB9EweYejuMgTeeUNcFe2ht553RUes/NAiCk=,tag:StfYaLPIv1bNHikbia+cPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUkpvUTZ0N3BhYVlmaW96
            RmViMm1paStHNExKVkplVXByelJaendDeTJFCkZRRnNBZ3RyMnNITmQ3cnJZMEhH
            bWtobTE4akhZT2Q4dEJHbnhjWWtSYTgKLS0tIElqNU5LcGllaTk2R1dwMTNiZzRj
            SGxTQ2NTeC9KQXNQT3hhaXZSaGRKWjgKPfuZL5NLaUFa+VZSEydgOhcDJqnmAEcm
            GHhRB6JbH1YwQIDLro9lRXF+m3eXomoF8/AJuC+dD31NKbTbtxWehQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkFpUGFyTGZMTHQyTWRG
            dU5hNXovM3BMbGh5T09KaC9OQ1RGUEVMMlVVCmJiRmZhWFdpQTV4dkhzcWxzM0Nh
            a1J5bWhXY3hLb2h3TmV3V0Z5ZnZ2TU0KLS0tIFhsNXVWVjV2V2k5Q1k4SGRpRkdn
            RlM2R1lxYlgxdUg3WE55MmZIVjIrd28KoL/IUT8wSzXktBOFvfciJodgxaIAj3WM
            Lv2hHy28NbInvxpCXuuy5wlxskCBiLXiBzVA3v0OE3WzV2RTC63s6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-09-19T19:30:13Z"
    mac: ENC[AES256_GCM,data:i1GxYEUpRvMGTpbrbp+yJJAipp7kUm5acdaL90o2WDmP1Ra+JxA+/ty5sdEbZJGNDJbYLvtGru+fABxggSvpc0Sy2ozwOuAxdFO0n8KcefKnW/LH5b5xfqn+vtp+ps90P93sLW8FkcMr35CaiV7MCl4m7QHG2mQkhselAFtdjB8=,iv:A+lyB3HVYUJ3btztDCly9Gv3Zi57AR3RjYxoXy6Ml3g=,tag:GNR22OBi/y/cp7oHJfMf4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
