apiVersion: ENC[AES256_GCM,data:6k8=,iv:CysZlg+fUQ+jilbhGvOox0KBFR29t06/Cb/Tw/HRwoM=,tag:1VgSX0+1GzROD4JuJ4RlYg==,type:str]
kind: ENC[AES256_GCM,data:A2Tkcyor,iv:OcIbRwkkCJyiSNBddHgCQDEtGwBMtd1AuKd+zSlqc/Y=,tag:BtKGl6LeSvGjyaFn6Jv0uQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:li1SjBq2aXHNZB3YlO6btGbKzG8X3odF,iv:9C1mHjLVmTeOEVqRYdIvrSFOMEjIxoTR97L5SIXXElE=,tag:5OT1B1ThnXY3wX7m+Zy3YA==,type:str]
    namespace: ENC[AES256_GCM,data:D0qKfxR4PE4q,iv:wCNmGX+04fnAqup8TlniY1EfXsYJUUxEtOU961ZkA/E=,tag:VrRnjaeDAHuyQ1NkCac8Ag==,type:str]
type: ENC[AES256_GCM,data:XIVjJ2eh,iv:RVAgHumc5mzQiIulcngk4L7MwDFBDUc4YRzpsn1pqoA=,tag:8l+qC3mWOqZG2sDznqFiBA==,type:str]
stringData:
    rclone.conf: ENC[AES256_GCM,data:OIV99JP17453DVypJQ0B7XxsQB/Zdpc9LwUGdv3dRq5utW7KWea99r2gO+5YXB3Bqxi1U80JEIXNi0BNcyifDLcAXyhZ9ZEZziy/1JvvJ7xk/o+CbMyfL/VnMeLEZU95oOxLNWEPibnxrhL68e3jV8NPhOByMA3OfTqK06yyGGH+jDd/ViI/GVgLNSIWU01+tiM8UINCx6h0RxYkvwV1tFYtA0E6BB5tiPReNILPvB4VBbNbbQOlM/YcuiEiHIjzod3fXLiKYRczeUkDqoNw0DLO76NhtrPhhwEUgNV4oFOLYeRo+Iq4IW1UzkihPmCyKXfEwz8sg0I/6oKljFC9pdNw7aJCLMXFDYwakwYG38TgHffwH0dXiafM/Mku2QGMm2Z5SDHKy9q+TS/PTZSy942ZDpJdlYrE6z+jsfhyEPkXjwkTFgYWAbP8Qk34rxOJXmM/O6pRSpVe89Esa1J1odlrH23iASKuMYMWpqGtG0O7SDa2LnMUJkTPDuIvO3ry2v2r8J22hDExnx6iXvPUGr/uDUvivuWQdWeQfVJC7k/q81y/1GGhCsPtfNsEiTtKSVbza73qH6GZ9h+Z8UiluLu6LjDINbf3u2Sq,iv:+RKP15EUJTpDTRzDP3Ep41hZdRLRMnGo0vDUL3sXvVk=,tag:UuDQLeLLhPwqhsIZhHXOBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WGovcnJLTExCRW9nbFo0
            TUo4TnRYT2s3MmhLRFpwamxDQlJuVXVMS1NnCmowTkc0b3hvSDcyYVVpaERIS1hL
            VFhFRURSSXFSc05qV2dTS1c0LzBPZUUKLS0tIGgrN1V1U2p1MkxBRWRmMEd6WUk4
            YzBhYXFsTWUzdXFwMkNhQytzaE15NTQK8yPEhZ8NS5/HCC7O+fXOQ4XNJDpVBcTy
            cxEuKL/xZbBodnAzss0SqOWK9duEbYgj5KsAV4tTWn2ogum0C+WPiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROHV4bkxiczhzZnhkY2Nm
            d0o3TkgxMjZIdkVQUytncXEwaHE1Sm94OUVBCktGTmsrNTFJaG90SUFnUGQ5dEcx
            UXpXaDVUWlFWbldXaHV5SUNSSmVvVWcKLS0tIGRYWmwzUnlmWmZTeFRDdGphREVZ
            NHlKYWZjcWpqanpGSTE2Q0Y5VEpkMncKkfD2PNWBtE9klc8Y/hzKuOwvHnMsB3wr
            K+9zZ1hr0iW1VLBFAw41pam7GSQ+st2x5WcwcOAtq3TMgsjoe+Qtag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
    lastmodified: "2026-08-08T14:52:34Z"
    mac: ENC[AES256_GCM,data:Yp6ap+sk+lRT90K24gz96FcyizACsYWwtnb7C2F3aa/248hNtK3bJyreF/Ryk+KY6inpBUP/dQC03FKx+iuBFsqJ47MYreoBAh81pyOTmRCSSM2Ke9JheOGOY6aGLh0zBvRZYD/c1UbbH5ahg8qZoTvivwvC9gPJhvKbUGn9dV8=,iv:chV58o0J7JwwYHyBwKDrmgD+RTaOhF/LB8T+Rt4hwWI=,tag:VnR7zwzLFRmRUzzZto5myQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
