apiVersion: ENC[AES256_GCM,data:/yU=,iv:7zxDFGAqvgojVmqhVwTXZD+NKp1qxN8NVmpawAsOz8k=,tag:MgGOp36EZSC3ZvPkmd8saQ==,type:str]
kind: ENC[AES256_GCM,data:YOJpxRy9,iv:qm+efbGlqvlrZXdNzIGkWMIpj+uGVWMceSce0EokPNE=,tag:2bBbPtjdKocRZSTOujxobg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vw5MAtqXgo3iqMFdiw==,iv:zCVhA6g72MxVaSqcvX4oOF9+3Ko6Bcqr3rNw4pDkHwI=,tag:f2CfXqkWbWpItdQVCYuWtw==,type:str]
    namespace: ENC[AES256_GCM,data:TZq9csYF,iv:qmGEn9U8Um4uarm2nbLnhkFvksbUZ0Nume21MNVvIbE=,tag:EYseQNk7wB+Ql3MYrVemoQ==,type:str]
type: ENC[AES256_GCM,data:vHGavxC3,iv:WAArAKdnhD2meQp4YTShqDv1TH3KQZXDccZ1f20KoLI=,tag:GUBN1KxkJyekfXnfuyeiVA==,type:str]
stringData:
    admin.password: ENC[AES256_GCM,data:jMNXL/T9C8CGrnHuqXXAUhwEff6QBq5khxl3obKKNJdTdSAFzaxuQ1jRQmnuuoQrz45nsPm1b2iJZFGb,iv:lTEEbsaMlGL0o0BIh04X1uDfu93+62ZIYgq2teGRkys=,tag:2qJ8JLjhodqnWBmBgB4gTQ==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:FcLWjWgOvz4Nnq0v/bnpVYfD6Fk=,iv:584gLwNvQri7YmFGwok/4TQpDiE2W102/Lsk8NECP3g=,tag:W/oBtu9z4AWOQCyvLEcGxg==,type:time]
    server.secretkey: ENC[AES256_GCM,data:YJ6nYxrqSj23gOXmmKBzKA9sEy+NF8ImPuiVgBWiWLLPGSNaoGlNli4nbyE=,iv:vANlvmuGTo4h1W7rc4VJo+oTQ1ff+/AWivlyqn6xMfc=,tag:oUPk7caGHEqsIsd778I/eQ==,type:str]
    oidc.authelia.clientSecret: ENC[AES256_GCM,data:Y6PTNaXw7ZrO8VDzI7mvwGmz5jAVDHpTQcJdqCqoI/A=,iv:Ld94bxAbF+1Jgc8uo7lj3fMJSe74Idz14jPZWYYqxmg=,tag:gPiPBMfNEeKnehjHc40ZTg==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMjFpYzB1Tm50WVErK0tK
            NmVJZzFRZm4wRkJNa2taUllpRlRScWMyR25JCjlaNk83Y2ZzOHpaY1VIVXNmNHNB
            Rm1sdHpUQytKU05hNVhjVE43ZVhwbG8KLS0tIFdGZmg3anZidzgwRE1nYVBkNjVm
            UGFtZ3lFb2FpYm5md242c2s4bEZ2bW8KVdNEDR/adSZZKAAyQXm7j29g0V91YN55
            Sx7FgApPglPA8c8lcKeTOuulhEwnu6mJXHkSwayTYIb8lrAIalOBKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWtUbDFmN0pSY2R2V0pI
            eEZra2VHOWtMTFloZlR1dWd6eE03YmpGQ2prCmcxZDM4RkgzYVVVdDBzV2VaTFcz
            MGJjRmU5RmQ5Y0x5R1ljMlpQMXBKQTgKLS0tIGNQY3pvc1pYejNjUFd6RWVYYk9F
            WlpzZzJrZlNEZ3FtWHJ1c2NvY0Q0c0EKLr+xe07EMVqj1JSX3D33xLbNSaK25weL
            d8pTpyDfawBviNVAKwKVFNSGj1mJAl90y7PN8ugK6BzsB9VYuqb/fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T22:59:38Z"
    mac: ENC[AES256_GCM,data:XPjcnCd/1eDGzc1e4FgjoFLA3pjsxW31IEVw2oIxYKKSKT/sEOHjSVnrcGIRJTAEcxtFNlqiwwTspb0NfzmWRya0tE9Ru2cwYOm1CREUliS6ifY0CVgcX84w5uvWZsYX6D5Wq3ar1zjg+4JZ9C09UnTfyQEHT+Nkvmxc6vPCPsc=,iv:lL7NGDYjHcnCD+ySTEAwH+75Q2y3sj0G8QHfxq6NViw=,tag:zWN9xnaAHeWqYZ5O/ZrTYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
