apiVersion: ENC[AES256_GCM,data:8Ik=,iv:em6fIvk6zkCTVbo8jXNwUZuCcrvGzv96uNWp8Fmgnqg=,tag:i0JpxxiwTbrMkzVIAS9Wzw==,type:str]
kind: ENC[AES256_GCM,data:rQY3cXPS,iv:R4jrPCU2FuEBbUp1ubiFlvZZQNeGjGl22C9NkD4Vie4=,tag:PG0lfUUOuCbhbKO+q2ZhJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mA+2JUHBJkg6tS6W,iv:VWGsUZoE+gvRZo79E/0OYdOXy2Gfr3dSl5x4fkkPIrQ=,tag:xR764fIKzqf93KX4FYyKiQ==,type:str]
    namespace: ENC[AES256_GCM,data:npkEyPQK,iv:MrnYiN+heOtMzFUy6CycDzvnP0vx7z7KTuWu7GZUhF8=,tag:hiW1/fmx67OkUiiltTxmpA==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:OcoYYWhllYPOjA==,iv:B42cV/jmgIT/u95CE/t6N3CjOVLJgOo8vcf63EpZ2SA=,tag:oyrE1K0gSDGAJB9tgnv3tw==,type:str]
stringData:
    url: ENC[AES256_GCM,data:5grp+3eXT8ZWgi/UEfN/ihQuZv9NKXr0,iv:xCD02YKvP7S/p70N3G09t2xoe1ulIwB1Vwg1654uzPw=,tag:Iw9NshkdhZdXjX9BTNfceg==,type:str]
    type: ENC[AES256_GCM,data:TvV2,iv:smzbaq40ImxxUOKz5cEFLHIsBb9FZJrkDR4oJmfzyls=,tag:HvhmNjIsH0QBnapl0oDoBQ==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:kaBKEXZAUSsqrkbiQxxAMwhsJOgxz878xY6apfnd6eQh7vt5nE5rSix19V2Jzn8ha6qyWTarmMnvxemTxw7nWbzVUGuEAH8IJRns9uNawOLlYS9cKkgYJGiT1G0ZYRgObKyzoAa+x7u1Twww+brrjdVrrquWzIAv3Ywixmg444uvLJ1I75p5XS9kLfwntbEFHzmjMTyxORheCvWH+FmX9fhlKpTI3QIgl8Yp5pmdaIhH6DZTtTGWH6gEy5BHvJu8F/AXl0URiJ1ExLPBAll35LWeeGqy0N3JgponEpiVmzcQWxDvN9gxW2CwrFeTkkh32nSKI6ZLtaeQ72sdZLWij1cAYm0uJHLfzYw9gpUabEBU0s8dQAJ9d5oqEEI+n28APW/GCoc9GtSu7TZyoeBWiA0BI6t9GUphkZvm4CEcbp5ay0e08J0UQHu0E3/+ADMhWiXg+iMmP6/yd492tmlu2WlJVp4Cbx90s7XL4eZNpwjOF3V0XZW9cWfmS4v7s3Nmcx891hLBfr0uAavi8S71,iv:CUNf+MXy8TuPrCCaYSfo1udY7W6ce1mhA6fudzSy44g=,tag:UbD42NLdwgJR9GJxp1nykQ==,type:str]
sops:
    age:
        - recipient: age1fxm6mx7zu5ygvxcqxq7aru4teht4eck7v5gln922jfyn7wx29gaszzp654
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbG1jVWJHUUN5d2lsT2RO
            NHpIZ2xrYXFiVHNFbElQekFsUjNTWnRzckJnClhUeG9mREdWOURtR2RjNHRyL0VB
            TVpQTXdlclJTbG05UkoyY1FMNXFzZW8KLS0tIFhrVHZYME81eU4zQzRNSnRxQmpL
            aGtiaGQwRDZaV0J1U1ZrcXZNK1VyR2cK6Xe64DrAarTIyG13IvliPYFYFTMDgZ+u
            laDhxMauK842I36uBTElz2QR/6uf9go8+emaBReghRXNYQmZk03mcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3kxpfxfwv92ldvxwlfz28gahancmj3v3d70g20ky372euaqzd8s0ne3hc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRclNrbkpLM0U1czNXZFdW
            YUo0bUM4eXlwZHBGOEp5QWI5UU1yR3pHdVRJCldIaEgyNGZVUXdRZUtlQ09GV0Nj
            S1lRNEhEM2ZJbjg4QnJ1bndteTkzaDAKLS0tIHFEOGNUb3RVZGhKbmNLdEhrNXpy
            WnNYVjBrVmpPV2I4cDFFcDVVRGtIUFUKOc7t07r9mpQY6SVI/+ltli3DRWjNJzjr
            Bf8bgAiGwiDlqQSN0gJUDqc0yuntyTXxVAd1Fic3GpMWQ2jg9DAWqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T21:13:23Z"
    mac: ENC[AES256_GCM,data:XTKVmOGF+5lCuXzB55FcTKvUdqvDEaJzbB9KVQRAuCvjph5fnLmmHl+mpKmYIjWHXUmjCSL6RDjllFnEyDigaIQwmOnVu9952lHmyD88zvE0D4W1MkwFSzCNJXXtFtFt1VZM6iGk73a1rjYRjT4aoBhVZr+qGU7GdQjmvDqB5fs=,iv:N724GrGmZlVpwIeHdCgLrZfyMmnWTa0lT7W3BARVAZk=,tag:jpQll8T4JRdjDIzD/s6ogQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
